[package]
name = "streaming-geocode"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

[dependencies]
common_failures = "0.1.1"
csv = "1.0.7"
env_logger = "0.6.1"
failure = "0.1.5"
futures-cpupool = "0.1.8"
futures-preview = { version = "0.3.0-alpha", features = ["compat"] }
hyper = "0.12"
hyper-tls = "0.3"
log = "0.4.6"
serde = "1.0.92"
# IMPORTANT: We require `preserve_order` to correctly handle "structure" JSON'
# specifications in a way that puts the right data in the right output columns.
serde_json = { version = "1.0.39", features = ["preserve_order"] }
structopt = "0.2.16"
tokio = "0.1"
url = "1.7.2"
