[package]
name = "streaming-geocode"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

[dependencies]
csv = "1.0.7"
failure = "0.1.5"
futures-preview = { version = "0.3.0-alpha", features = ["compat"] }
hyper = "0.12"
hyper-tls = "0.3"
reqwest = "0.9.18"
serde = "1.0.92"
serde_json = "1.0.39"
tokio = "0.1"
url = "1.7.2"
